export const PROJECTS = [
  {
    name: 'Davivienda',
    description: 'Bank Application for Colombia and Central America',
    platform: 'Mobile',
    sector: 'Finance',
    icon: '/images/davivienda.jpeg',
    url: 'https://apps.apple.com/us/app/davivienda-m%C3%B3vil/id909149607',
  },
  {
    name: 'Bancolombia',
    description: 'Colombian Bank',
    platform: 'Web/Mobile',
    sector: 'Finance',
    icon: '/images/bancolombia.png',
    url: 'https://www.bancolombia.com/personas',
  },
  {
    name: 'Open Bank',
    description: 'Santander Bank Open banking',
    platform: 'Web',
    sector: 'Finance',
    icon: '/images/openbank.svg',
    url: 'https://www.openbank.es/',
  },
  {
    name: 'Fanalyst',
    description: 'Social network for sports',
    platform: 'Mobile',
    sector: 'Sports',
    icon: '/images/fanalyst.webp',
    url: 'https://apps.apple.com/us/app/fanalyst/id1589482962',
  },
  {
    name: 'CommentUp',
    description: 'AI Platform',
    platform: 'Mobile/Web',
    sector: 'AI',
    icon: '/logo.png',
    url: 'https://apps.apple.com/pa/app/id1665658655',
  },
  {
    name: 'Finmobi',
    description: 'Fintech for real estate in Latam',
    platform: 'Web',
    sector: 'Fintech',
    icon: '/images/finmobi.png',
    url: 'https://finmobi.co',
  },
  {
    name: 'Cash Rent',
    description: 'The easiest way to lease, buy and sell ground',
    platform: 'Mobile/Web',
    sector: 'Real Estate',
    icon: '/images/cashrent.png',
    url: 'https://apps.apple.com/us/app/cashrent/id1493288436',
  },
  {
    name: 'Trufyx',
    description: 'Platform for reparing devices in EEUU',
    platform: 'Mobile',
    sector: 'Services',
    icon: '/images/trufyx.png',
    url: 'https://apps.apple.com/us/app/trufyx-technician/id1553995455',
  },
  {
    name: 'Indigo Donations',
    description: 'Application for Donations',
    platform: 'Mobile',
    sector: 'Non Profit',
    icon: '/images/indigo.png',
    url: 'https://apps.apple.com/mn/app/indigo-donations/id1566088228',
  },
];
